### ISSUE TITLE
Error when trying to import the bootstrap.scss 

### ISSUE THREAD

**Issue by tharakabimal** [juliancwirko/meteor-bootstrap-npm-test#1]
I am getting  the following err. can you tell me what I'm doing wrong here?

```
While processing files with fourseven:scss (for target web.browser):
/client/modules/core/scss/main.scss: Scss compiler error: File to import:
{}/node_modules/bootstrap/scss/bootstrap.scss not found in file:
/home/tharaka/My
Projects/mantra/mantra_blog/{}/client/modules/core/scss/main.scss
```

A link to my repo : https://github.com/tharakabimal/blog-app/blob/master/client/modules/core/scss/main.scss

Thanks.

**Comment by juliancwirko** [comment]
It will work only for Meteor 1.3.2 and above. You have 1.3.1. But you can update your project by `meteor update --release 1.3.2.1` and it should work.

**Comment by tharakabimal** [comment]
Nice it's working fine. Thanks.

**Comment by tharakabimal** [comment]
@juliancwirko  I just tried importing font-awesome css, and I'm getting this error.

```
While processing files with fourseven:scss (for target web.browser):
/client/modules/core/scss/main.scss: Scss compiler error: Undefined
variable: "$fa-font-path".
```

**Comment by juliancwirko** [comment]
In this variable you need to configure the path to your font files. I think the best approach to integrate font awesome in Meteor is:

``` html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>
```

So you don't need to wory about importing Font Awesome and you get it from CDN

**Comment by tharakabimal** [comment]
Noted. Thanks
